### ISSUE TITLE
Should I use this repo for PRs?

### ISSUE THREAD

**Issue by YakovL** [abego/YourSearchPlugin#4]
Hey Udo!

I've done some updates to the plugin (see [here](https://github.com/YakovL/TiddlyWiki_YourSearchPlugin/commits/dev)), should I create PRs here, or you prefer not to deal with this and I'd better reshape my fork as I see fit and suggest that one should refer to it instead?

**Comment by abego** [comment]
Hi Yakov!

Thanks for your interest in the YourSearchPlugin and the work you invested in it.

Just create PRs and I will integrate your changes. However, as I am quite busy the next days, don’t expect the merge to happen before the weekend.

Udo

**Comment by YakovL** [comment]
Right, take your time!

https://github.com/abego/YourSearchPlugin/pull/5
